config/routes.rb
Rails.application.routes.draw do
  get '/' => 'main#index'

  resources :task_types
  resources :tasks

end

app/models/concerns/schedulable.rb
module Schedulable
  extend ActiveSupport::Concern

  require 'rufus-scheduler'
  require 'net/http'


  # Schedules the task using rufus-scheduler
  def schedule
    s = Rufus::Scheduler.new

    # assign job id to the instance including this module
    self.job_id =
        s.cron cron_script() do
          call_agent
        end

    # update the model
    self.save!
    puts "Created job: #{self.job_id}"

  end

  # calls this task's agent
  def call_agent
    puts 'Running job: ' +self.to_s
    puts "Calling agent on #{agent}"

    url = URI.parse self.agent
    response = Net::HTTP.post_form url, { :agent_key => self.agent_key, :execution_path => self.executable_path, :task_name => self.name }

    puts "Received response from agent: #{response}"
  end

  # Returns the corresponding cron_script for this Task
  def cron_script
    days = self.scheduled_days
    t = self.start_time
    sc = "%d %d %d * * %s" % [t.sec, t.min, t.hour, days]
    puts "Scheduling cron job (#{sc})"
    sc
  end

  # Looks up job id and unschedules it
  def unschedule
    s = Rufus::Scheduler.new
    job = s.job self.job_id

    #inly unschedule if we can find the job
    if not job.nil?
      job.unschedule

      puts "Destroyed job: #{self.job_id}"

      # update the model
      self.save!
    else
      puts "The job (#{self.job_id}) was not found!"
    end

  end


end

app/models/task.rb
class Task < ActiveRecord::Base
  include Schedulable

  validates_presence_of :executable_path, :agent, :agent_key, :scheduled_days
  validates_length_of :executable_path, :agent_key, :agent, minimum: 3

  # dummy days field to hold selected days
  attr_accessor :days

  # scheduled tasks that have not yet been executed
  scope :for_today, -> { where('scheduled_days like ?', "%#{Date.today.strftime('%A')[1...3]}%") }

  # sets the scheduled_days to the ones stored on the #days attribute
  def set_days
    self.scheduled_days = self.days.drop(1).collect { |s| s[0...3] }.join(',').upcase # drop the first param as it comes nil
  end

end

app/models/task_type.rb
class TaskType < ActiveRecord::Base
  validates_presence_of :name, :description
  validates_length_of :name, :description, minimum: 5
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    @Tasks = Task.for_today
  end
end

app/controllers/task_types_controller.rb
class TaskTypesController < ApplicationController
  before_action :set_task_type, only: [:show, :edit, :update, :destroy]

  # GET /task_types
  # GET /task_types.json
  def index
    @task_types = TaskType.all
  end

  # GET /task_types/1
  # GET /task_types/1.json
  def show
  end

  # GET /task_types/new
  def new
    @task_type = TaskType.new
  end

  # GET /task_types/1/edit
  def edit
  end

  # POST /task_types
  # POST /task_types.json
  def create
    @task_type = TaskType.new(task_type_params)

    respond_to do |format|
      if @task_type.save
        format.html { redirect_to @task_type, notice: 'Task type was successfully created.' }
        format.json { render :show, status: :created, location: @task_type }
      else
        format.html { render :new }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /task_types/1
  # PATCH/PUT /task_types/1.json
  def update
    respond_to do |format|
      if @task_type.update(task_type_params)
        format.html { redirect_to @task_type, notice: 'Task type was successfully updated.' }
        format.json { render :show, status: :ok, location: @task_type }
      else
        format.html { render :edit }
        format.json { render json: @task_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /task_types/1
  # DELETE /task_types/1.json
  def destroy
    @task_type.destroy
    respond_to do |format|
      format.html { redirect_to task_types_url, notice: 'Task type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_task_type
      @task_type = TaskType.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def task_type_params
      params.require(:task_type).permit(:name, :description)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [:show, :edit, :update, :destroy]
  before_action :fetch_types

  # GET /tasks
  # GET /tasks.json
  def index
    @tasks = Task.all
  end

  # GET /tasks/1
  # GET /tasks/1.json
  def show
  end

  # GET /tasks/new
  def new
    @task = Task.new
  end

  # GET /tasks/1/edit
  def edit
  end

  # POST /tasks
  # POST /tasks.json
  def create
    @task = Task.new(task_params)
    @task.set_days
    saved = @task.save

    # schedule the task only if it was saved correctly
    @task.schedule if saved

    respond_to do |format|
      if saved
        format.html { redirect_to @task, notice: 'Task was successfully created.' }
        format.json { render :show, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tasks/1
  # PATCH/PUT /tasks/1.json
  def update
    updated = @task.update(task_params)

    if updated
      @task.set_days
      @task.schedule
      @task.save!
    end

    respond_to do |format|
      if updated
        format.html { redirect_to @task, notice: 'Task was successfully updated.' }
        format.json { render :show, status: :ok, location: @task }
      else
        format.html { render :edit }
        format.json { render json: @task.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tasks/1
  # DELETE /tasks/1.json
  def destroy
    #unschedule before destroying
    @task.unschedule
    @task.destroy
    respond_to do |format|
      format.html { redirect_to tasks_url, notice: 'Task was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_task
    @task = Task.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def task_params
    params.require(:task).permit(:name, :executable_path, :start_time, :end_time, :agent, :agent_key, :days => [])
  end

  def fetch_types
    @types = TaskType.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/main_helper.rb
module MainHelper
end

app/helpers/task_types_helper.rb
module TaskTypesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
  def days_options
    ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday']
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CoTaskerServer</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
  <header class="mdl-layout__header">
    <div class="mdl-layout__header-row">
      <span class="mdl-layout-title">Tasker server</span>

      <div class="mdl-layout-spacer"></div>
      <nav class="mdl-navigation mdl-layout--large-screen-only">
        <%= link_to :Home, '/', { :class => 'mdl-navigation__link' } %>
        <%= link_to :Tasks, tasks_path, { :class => 'mdl-navigation__link' } %>
        <%= link_to 'Task Types', task_types_path, { :class => 'mdl-navigation__link' } %>
      </nav>
    </div>
  </header>
  <main class="mdl-layout__content">
    <div class="page-container">
      <div class="page-content">
        <%= yield %>
      </div>
    </div>


  </main>
</div>


</body>
</html>

app/views/main/index.html.erb
<h3>Scheduled Tasks for Today</h3>

<ul class="list-tasks">
  <% @Tasks.each do |task| %>
      <li>
        <div class="mdl-card mdl-shadow--2dp">

          <div class="mdl-card__title mdl-card--expand">
            <h4>
              <%= "#{task.name} on agent: #{task.agent}" %><br>
              <%= task.scheduled_days %><br>
              <%= "#{task.start_time.hour}:#{task.start_time.min} - #{task.end_time.hour}:#{task.end_time.min}" %>
            </h4>
          </div>
          <div class="mdl-card__actions mdl-card--border">
            <%= link_to "Go to Task", task, { :class => 'mdl-button mdl-button--colored mdl-js-button mdl-js-ripple-effect' } %>
            <div class="mdl-layout-spacer"></div>
          </div>

        </div>
      </li>
  <% end %>
</ul>

app/views/task_types/_form.html.erb
<%= form_for(@task_type) do |f| %>
  <% if @task_type.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task_type.errors.count, "error") %> prohibited this task_type from being saved:</h2>

      <ul>
      <% @task_type.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_field :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/task_types/edit.html.erb
<h1>Editing Task Type</h1>

<%= render 'form' %>

<%= link_to 'Show', @task_type %> |
<%= link_to 'Back', task_types_path %>

app/views/task_types/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Task Types</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @task_types.each do |task_type| %>
      <tr>
        <td><%= task_type.name %></td>
        <td><%= task_type.description %></td>
        <td><%= link_to 'Show', task_type %></td>
        <td><%= link_to 'Edit', edit_task_type_path(task_type) %></td>
        <td><%= link_to 'Destroy', task_type, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task type', new_task_type_path %>

app/views/task_types/new.html.erb
<h1>New Task Type</h1>

<%= render 'form' %>

<%= link_to 'Back', task_types_path %>

app/views/task_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task_type.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @task_type.description %>
</p>

<%= link_to 'Edit', edit_task_type_path(@task_type) %> |
<%= link_to 'Back', task_types_path %>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
    <% if @task.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

          <ul>
            <% @task.errors.full_messages.each do |message| %>
                <li><%= message %></li>
            <% end %>
          </ul>
        </div>
    <% end %>

    <div class="field">
      <%= f.label :name %><br>
      <%= f.select :name, @types.all.collect { |t| t.name } %>
    </div>
    <div class="field">
      <%= f.label :executable_path %><br>
      <%= f.text_field :executable_path %>
    </div>
    <div class="field">
      <%= f.label :start_time %><br>
      <%= f.time_select :start_time %>
    </div>
    <div class="field">
      <%= f.label :end_time %><br>
      <%= f.time_select :end_time %>
    </div>
    <div class="field">
      <%= f.label :scheduled_days %><br>
      <%= f.select :days, days_options, {}, {:multiple => true, :size => 5} %>
    </div>
    <div class="field">
      <%= f.label :agent %><br>
      <%= f.text_field :agent %>
    </div>
    <div class="field">
      <%= f.label :agent_key %><br>
      <%= f.text_field :agent_key %>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
<% end %>

app/views/tasks/edit.html.erb
<h1>Editing Task</h1>

<%= render 'form' %>

<%= link_to 'Show', @task %> |
<%= link_to 'Back', tasks_path %>

app/views/tasks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tasks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Executable path</th>
      <th>Start time</th>
      <th>End time</th>
      <th>Scheduled days</th>
      <th>Agent</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.name %></td>
        <td><%= task.executable_path %></td>
        <td><%= task.start_time %></td>
        <td><%= task.end_time %></td>
        <td><%= task.scheduled_days %></td>
        <td><%= task.agent %></td>
        <td><%= link_to 'Show', task %></td>
        <td><%= link_to 'Edit', edit_task_path(task) %></td>
        <td><%= link_to 'Destroy', task, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Task', new_task_path %>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<%= link_to 'Back', tasks_path %>

app/views/tasks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @task.name %>
</p>

<p>
  <strong>Executable path:</strong>
  <%= @task.executable_path %>
</p>

<p>
  <strong>Start time:</strong>
  <%= @task.start_time %>
</p>

<p>
  <strong>End time:</strong>
  <%= @task.end_time %>
</p>

<p>
  <strong>Scheduled days:</strong>
  <%= @task.scheduled_days %>
</p>

<p>
  <strong>Agent:</strong>
  <%= @task.agent %>
</p>

<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>